services:
  opensearch:
    image: opensearchproject/opensearch:2.10.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - plugins.security.disabled=true
    ports:
      - 9200:9200
    volumes:
      - osdata:/usr/share/opensearch/data
volumes:
  osdata:
